project:
  type: website
website:
  title: "GHUY'S SILVA RERUM"
  navbar:
    right:
      - text: Memories
        file: memories.qmd  
      - text: Publications
        file: publications.qmd
      - text: Test
        file: test.qmd
      - about.qmd  
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.scss




